# -*- coding: utf-8 -*-
"""Major_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15D7YR2ZoXbIvZBd-wIWz2JaN4dOBeDPP
"""

pip install streamlit opencv-python deepface

import streamlit as st
import cv2
import numpy as np
from deepface import DeepFace

!pip install pyngrok
!pip install streamlit opencv-python deepface

# Write the Streamlit app code to app.py
with open('app.py', 'w') as f:
    f.write('''
import streamlit as st
import cv2
import numpy as np
from deepface import DeepFace

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
    return faces

def predict_age_gender(image, face):
    x, y, w, h = face
    face_img = image[y:y+h, x:x+w]
    face_img_rgb = cv2.cvtColor(face_img, cv2.COLOR_BGR2RGB)
    predictions = DeepFace.analyze(face_img_rgb, actions=['age', 'gender'], enforce_detection=False)
    age = predictions[0]['age']
    gender = "Male" if predictions[0]['gender'] == 'Man' else "Female"
    return age, gender

st.title("Age and Gender Detection")
st.write("Upload an image to detect the age and gender of the faces in the image.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
if uploaded_file is not None:
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
    image = cv2.imdecode(file_bytes, 1)
    faces = preprocess_image(image)
    if len(faces) > 0:
        for face in faces:
            age, gender = predict_age_gender(image, face)
            x, y, w, h = face
            cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
            text = f"Age: {age}, Gender: {gender}"
            cv2.putText(image, text, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
        st.image(image, channels="BGR", use_column_width=True)
    else:
        st.write("No faces detected.")
    ''')

from pyngrok import ngrok

# Set your ngrok authtoken
ngrok.set_auth_token("2k3z2BHQISJazge6P45eHk0SoMG_5C7fLS5ybApaWygMAhnNz")

# Start ngrok
public_url = ngrok.connect(addr="8501")
print(f'Public URL: {public_url}')

# Run the Streamlit app
!streamlit run app.py &

# Keep the tunnel open
import time
while True:
    time.sleep(1)
